// <auto-generated />
using System;
using System.Collections.Generic;
using AutoAuctionPlayground.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AutoAuctionPlayground.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AutoAuctionDbContext))]
    [Migration("20260920142655_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AutoAuctionPlayground.Domain.Entities.Auctions.Auction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("EndsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ends_at");

                    b.Property<Guid?>("HighestBidderUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("highest_bidder_user_id");

                    b.Property<Guid>("SellerCompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("seller_company_id");

                    b.Property<Guid>("SellerUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("seller_user_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<Guid>("VehicleListingId")
                        .HasColumnType("uuid")
                        .HasColumnName("vehicle_listing_id");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "HighestBidAmount", "AutoAuctionPlayground.Domain.Entities.Auctions.Auction.HighestBidAmount#Money", b1 =>
                        {
                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric(12,2)")
                                .HasColumnName("highest_bid_amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("highest_bid_currency");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "StartingPrice", "AutoAuctionPlayground.Domain.Entities.Auctions.Auction.StartingPrice#Money", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric(12,2)")
                                .HasColumnName("starting_price_amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("starting_price_currency");
                        });

                    b.HasKey("Id")
                        .HasName("pk_auctions");

                    b.HasIndex("HighestBidderUserId")
                        .HasDatabaseName("ix_auctions_highest_bidder_user_id");

                    b.HasIndex("SellerCompanyId")
                        .HasDatabaseName("ix_auctions_seller_company_id");

                    b.HasIndex("SellerUserId")
                        .HasDatabaseName("ix_auctions_seller_user_id");

                    b.HasIndex("VehicleListingId")
                        .IsUnique()
                        .HasDatabaseName("ix_auctions_one_open_per_listing")
                        .HasFilter("status = 'Open'");

                    b.HasIndex("Status", "EndsAt")
                        .HasDatabaseName("ix_auctions_status_ends_at");

                    b.ToTable("auctions", (string)null);
                });

            modelBuilder.Entity("AutoAuctionPlayground.Domain.Entities.Auctions.AuctionBid", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AuctionId")
                        .HasColumnType("uuid")
                        .HasColumnName("auction_id");

                    b.Property<Guid>("BidderUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("bidder_user_id");

                    b.Property<DateTime>("PlacedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("placed_at");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Amount", "AutoAuctionPlayground.Domain.Entities.Auctions.AuctionBid.Amount#Money", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric(12,2)")
                                .HasColumnName("amount_amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("amount_currency");
                        });

                    b.HasKey("Id")
                        .HasName("pk_auction_bids");

                    b.HasIndex("BidderUserId")
                        .HasDatabaseName("ix_auction_bids_bidder_user_id");

                    b.HasIndex("AuctionId", "PlacedAt")
                        .HasDatabaseName("ix_auction_bids_auction_id_placed_at");

                    b.ToTable("auction_bids", (string)null);
                });

            modelBuilder.Entity("AutoAuctionPlayground.Domain.Entities.Companies.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_companies");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_companies_name");

                    b.ToTable("companies", (string)null);
                });

            modelBuilder.Entity("AutoAuctionPlayground.Domain.Entities.Transactions.VehicleTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AuctionId")
                        .HasColumnType("uuid")
                        .HasColumnName("auction_id");

                    b.Property<Guid>("BuyerUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("buyer_user_id");

                    b.Property<DateTime>("FinalizedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finalized_at");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("kind");

                    b.Property<Guid>("VehicleListingId")
                        .HasColumnType("uuid")
                        .HasColumnName("vehicle_listing_id");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "FinalPrice", "AutoAuctionPlayground.Domain.Entities.Transactions.VehicleTransaction.FinalPrice#Money", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric(12,2)")
                                .HasColumnName("final_price_amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("final_price_currency");
                        });

                    b.HasKey("Id")
                        .HasName("pk_vehicle_transactions");

                    b.HasIndex("AuctionId")
                        .IsUnique()
                        .HasDatabaseName("ix_vehicle_transactions_one_per_auction")
                        .HasFilter("auction_id IS NOT NULL");

                    b.HasIndex("BuyerUserId")
                        .HasDatabaseName("ix_vehicle_transactions_buyer_user_id");

                    b.HasIndex("VehicleListingId")
                        .IsUnique()
                        .HasDatabaseName("ix_vehicle_transactions_one_per_listing");

                    b.ToTable("vehicle_transactions", (string)null);
                });

            modelBuilder.Entity("AutoAuctionPlayground.Domain.Entities.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("CompanyId")
                        .HasDatabaseName("ix_users_company_id");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("AutoAuctionPlayground.Domain.Entities.Vehicle.ListingPriceChange", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("changed_at");

                    b.Property<Guid>("ChangedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("changed_by_user_id");

                    b.Property<Guid>("VehicleListingId")
                        .HasColumnType("uuid")
                        .HasColumnName("vehicle_listing_id");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "NewPrice", "AutoAuctionPlayground.Domain.Entities.Vehicle.ListingPriceChange.NewPrice#Money", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric(12,2)")
                                .HasColumnName("new_price_amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("new_price_currency");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "OldPrice", "AutoAuctionPlayground.Domain.Entities.Vehicle.ListingPriceChange.OldPrice#Money", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric(12,2)")
                                .HasColumnName("old_price_amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("old_price_currency");
                        });

                    b.HasKey("Id")
                        .HasName("pk_listing_price_changes");

                    b.HasIndex("VehicleListingId", "ChangedAt")
                        .HasDatabaseName("ix_listing_price_changes_vehicle_listing_id_changed_at");

                    b.ToTable("listing_price_changes", (string)null);
                });

            modelBuilder.Entity("AutoAuctionPlayground.Domain.Entities.Vehicle.VehicleListing", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("DealerCompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("dealer_company_id");

                    b.Property<Guid>("DealerId")
                        .HasColumnType("uuid")
                        .HasColumnName("dealer_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("VehicleModelId")
                        .HasColumnType("uuid")
                        .HasColumnName("vehicle_model_id");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Details", "AutoAuctionPlayground.Domain.Entities.Vehicle.VehicleListing.Details#VehicleListingDetails", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<int>("MileageKm")
                                .HasColumnType("integer")
                                .HasColumnName("mileage_km");

                            b1.Property<string>("Vin")
                                .IsRequired()
                                .HasMaxLength(17)
                                .HasColumnType("character varying(17)")
                                .HasColumnName("vin");

                            b1.Property<int>("Year")
                                .HasColumnType("integer")
                                .HasColumnName("year");

                            b1.ComplexProperty(typeof(Dictionary<string, object>), "Price", "AutoAuctionPlayground.Domain.Entities.Vehicle.VehicleListing.Details#VehicleListingDetails.Price#Money", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.Property<decimal>("Amount")
                                        .HasColumnType("numeric(12,2)")
                                        .HasColumnName("price_amount");

                                    b2.Property<string>("Currency")
                                        .IsRequired()
                                        .HasMaxLength(3)
                                        .HasColumnType("character varying(3)")
                                        .HasColumnName("price_currency");
                                });
                        });

                    b.HasKey("Id")
                        .HasName("pk_vehicle_listings");

                    b.HasIndex("DealerCompanyId")
                        .HasDatabaseName("ix_vehicle_listings_dealer_company_id");

                    b.HasIndex("DealerId")
                        .HasDatabaseName("ix_vehicle_listings_dealer_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_vehicle_listings_status");

                    b.HasIndex("VehicleModelId")
                        .HasDatabaseName("ix_vehicle_listings_vehicle_model_id");

                    b.ToTable("vehicle_listings", (string)null);
                });

            modelBuilder.Entity("AutoAuctionPlayground.Domain.Entities.Vehicle.VehicleMake", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_vehicle_makes");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_vehicle_makes_name");

                    b.ToTable("vehicle_makes", (string)null);
                });

            modelBuilder.Entity("AutoAuctionPlayground.Domain.Entities.Vehicle.VehicleModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<int?>("ProductionEndYear")
                        .HasColumnType("integer")
                        .HasColumnName("production_end_year");

                    b.Property<int>("ProductionStartYear")
                        .HasColumnType("integer")
                        .HasColumnName("production_start_year");

                    b.Property<Guid>("VehicleMakeId")
                        .HasColumnType("uuid")
                        .HasColumnName("vehicle_make_id");

                    b.HasKey("Id")
                        .HasName("pk_vehicle_models");

                    b.HasIndex("VehicleMakeId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_vehicle_models_vehicle_make_id_name");

                    b.ToTable("vehicle_models", (string)null);
                });

            modelBuilder.Entity("AutoAuctionPlayground.Domain.Entities.Auctions.Auction", b =>
                {
                    b.HasOne("AutoAuctionPlayground.Domain.Entities.Users.User", null)
                        .WithMany()
                        .HasForeignKey("HighestBidderUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_auctions_users_highest_bidder_user_id");

                    b.HasOne("AutoAuctionPlayground.Domain.Entities.Companies.Company", null)
                        .WithMany()
                        .HasForeignKey("SellerCompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_auctions_companies_seller_company_id");

                    b.HasOne("AutoAuctionPlayground.Domain.Entities.Users.User", null)
                        .WithMany()
                        .HasForeignKey("SellerUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_auctions_users_seller_user_id");

                    b.HasOne("AutoAuctionPlayground.Domain.Entities.Vehicle.VehicleListing", null)
                        .WithMany()
                        .HasForeignKey("VehicleListingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_auctions_vehicle_listings_vehicle_listing_id");
                });

            modelBuilder.Entity("AutoAuctionPlayground.Domain.Entities.Auctions.AuctionBid", b =>
                {
                    b.HasOne("AutoAuctionPlayground.Domain.Entities.Auctions.Auction", null)
                        .WithMany("Bids")
                        .HasForeignKey("AuctionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_auction_bids_auctions_auction_id");

                    b.HasOne("AutoAuctionPlayground.Domain.Entities.Users.User", null)
                        .WithMany()
                        .HasForeignKey("BidderUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_auction_bids_users_bidder_user_id");
                });

            modelBuilder.Entity("AutoAuctionPlayground.Domain.Entities.Transactions.VehicleTransaction", b =>
                {
                    b.HasOne("AutoAuctionPlayground.Domain.Entities.Auctions.Auction", null)
                        .WithMany()
                        .HasForeignKey("AuctionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_vehicle_transactions_auctions_auction_id");

                    b.HasOne("AutoAuctionPlayground.Domain.Entities.Users.User", null)
                        .WithMany()
                        .HasForeignKey("BuyerUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_vehicle_transactions_users_buyer_user_id");

                    b.HasOne("AutoAuctionPlayground.Domain.Entities.Vehicle.VehicleListing", null)
                        .WithMany()
                        .HasForeignKey("VehicleListingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_vehicle_transactions_vehicle_listings_vehicle_listing_id");
                });

            modelBuilder.Entity("AutoAuctionPlayground.Domain.Entities.Users.User", b =>
                {
                    b.HasOne("AutoAuctionPlayground.Domain.Entities.Companies.Company", "Company")
                        .WithMany("Users")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_users_companies_company_id");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("AutoAuctionPlayground.Domain.Entities.Vehicle.ListingPriceChange", b =>
                {
                    b.HasOne("AutoAuctionPlayground.Domain.Entities.Vehicle.VehicleListing", null)
                        .WithMany("PriceHistory")
                        .HasForeignKey("VehicleListingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_listing_price_changes_vehicle_listings_vehicle_listing_id");
                });

            modelBuilder.Entity("AutoAuctionPlayground.Domain.Entities.Vehicle.VehicleListing", b =>
                {
                    b.HasOne("AutoAuctionPlayground.Domain.Entities.Companies.Company", null)
                        .WithMany()
                        .HasForeignKey("DealerCompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_vehicle_listings_companies_dealer_company_id");

                    b.HasOne("AutoAuctionPlayground.Domain.Entities.Users.User", null)
                        .WithMany()
                        .HasForeignKey("DealerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_vehicle_listings_users_dealer_id");

                    b.HasOne("AutoAuctionPlayground.Domain.Entities.Vehicle.VehicleModel", "Model")
                        .WithMany()
                        .HasForeignKey("VehicleModelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_vehicle_listings_vehicle_models_vehicle_model_id");

                    b.Navigation("Model");
                });

            modelBuilder.Entity("AutoAuctionPlayground.Domain.Entities.Vehicle.VehicleModel", b =>
                {
                    b.HasOne("AutoAuctionPlayground.Domain.Entities.Vehicle.VehicleMake", "Make")
                        .WithMany("Models")
                        .HasForeignKey("VehicleMakeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_vehicle_models_vehicle_makes_vehicle_make_id");

                    b.Navigation("Make");
                });

            modelBuilder.Entity("AutoAuctionPlayground.Domain.Entities.Auctions.Auction", b =>
                {
                    b.Navigation("Bids");
                });

            modelBuilder.Entity("AutoAuctionPlayground.Domain.Entities.Companies.Company", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("AutoAuctionPlayground.Domain.Entities.Vehicle.VehicleListing", b =>
                {
                    b.Navigation("PriceHistory");
                });

            modelBuilder.Entity("AutoAuctionPlayground.Domain.Entities.Vehicle.VehicleMake", b =>
                {
                    b.Navigation("Models");
                });
#pragma warning restore 612, 618
        }
    }
}
